# Generated by Django 4.2.11 on 2024-05-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_questionmodel_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='answer',
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='text_of_answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
