# Generated by Django 4.2.11 on 2024-05-03 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_remove_questionmodel_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.answermodel'),
            preserve_default=False,
        ),
    ]
