# Generated by Django 4.2.11 on 2024-05-04 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_alter_questionmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answermodel',
            options={'verbose_name': 'Установочная модель опросов', 'verbose_name_plural': 'Установочная модель опросов'},
        ),
        migrations.AlterModelOptions(
            name='datamodel',
            options={'verbose_name': 'Поле собранных данных опросов.', 'verbose_name_plural': 'Поле собранных данных опросов.'},
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_questions', to='survey.questionmodel', verbose_name='Следующий вопрос, если выбран этот ответ'),
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.questionmodel', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='text_of_answer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ответ на вопрос'),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.answermodel', verbose_name='Ответ на вопрос'),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.questionmodel', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveymodel', verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.answermodel'),
        ),
    ]
